In [1]:
import pandas as pd

In [5]:
df=pd.read_csv('sales1_data.csv')

df.head(5)

         Date   Product  Sales Region
0  2023-01-01  Product3  738.0   West
1  2023-01-02  Product2  868.0  North
2  2023-01-03  Product2  554.0   West
3  2023-01-04  Product1  618.0  South
4  2023-01-05  Product3  501.0   East

In [6]:
df.tail(5)

          Date   Product  Sales Region
20  2023-01-21  Product2    NaN   West
21  2023-01-22  Product3  296.0   West
22  2023-01-23  Product2  737.0   West
23  2023-01-24  Product3  531.0   East
24  2023-01-25  Product2  834.0  North

In [7]:
df.describe()

            Sales
count   19.000000
mean   554.000000
std    231.543372
min    124.000000
25%    381.500000
50%    554.000000
75%    737.500000
max    868.000000

In [8]:
df.dtypes

Date        object
Product     object
Sales      float64
Region      object
dtype: object

In [12]:
#Handling Missing Value

df[df.isnull()]

   Date Product  Sales Region
0   NaN     NaN    NaN    NaN
1   NaN     NaN    NaN    NaN
2   NaN     NaN    NaN    NaN
3   NaN     NaN    NaN    NaN
4   NaN     NaN    NaN    NaN
5   NaN     NaN    NaN    NaN
6   NaN     NaN    NaN    NaN
7   NaN     NaN    NaN    NaN
8   NaN     NaN    NaN    NaN
9   NaN     NaN    NaN    NaN
10  NaN     NaN    NaN    NaN
11  NaN     NaN    NaN    NaN
12  NaN     NaN    NaN    NaN
13  NaN     NaN    NaN    NaN
14  NaN     NaN    NaN    NaN
15  NaN     NaN    NaN    NaN
16  NaN     NaN    NaN    NaN
17  NaN     NaN    NaN    NaN
18  NaN     NaN    NaN    NaN
19  NaN     NaN    NaN    NaN
20  NaN     NaN    NaN    NaN
21  NaN     NaN    NaN    NaN
22  NaN     NaN    NaN    NaN
23  NaN     NaN    NaN    NaN
24  NaN     NaN    NaN    NaN

In [13]:
df.isnull().any(axis=1)

0     False
1     False
2     False
3     False
4     False
5      True
6     False
7     False
8     False
9     False
10    False
11     True
12     True
13    False
14    False
15    False
16     True
17     True
18    False
19    False
20     True
21    False
22    False
23    False
24    False
dtype: bool

In [14]:
df.isnull().any()

Date       False
Product    False
Sales       True
Region     False
dtype: bool

In [15]:
df.isnull().sum()

Date       0
Product    0
Sales      6
Region     0
dtype: int64

In [16]:
df.fillna(0)

          Date   Product  Sales Region
0   2023-01-01  Product3  738.0   West
1   2023-01-02  Product2  868.0  North
2   2023-01-03  Product2  554.0   West
3   2023-01-04  Product1  618.0  South
4   2023-01-05  Product3  501.0   East
5   2023-01-06  Product1    0.0   West
6   2023-01-07  Product3  339.0  South
7   2023-01-08  Product3  280.0  South
8   2023-01-09  Product2  806.0  North
9   2023-01-10  Product2  816.0  South
10  2023-01-11  Product3  469.0   West
11  2023-01-12  Product3    0.0   East
12  2023-01-13  Product3    0.0   East
13  2023-01-14  Product3  676.0   East
14  2023-01-15  Product1  183.0  South
15  2023-01-16  Product1  424.0  South
16  2023-01-17  Product1    0.0  South
17  2023-01-18  Product1    0.0  South
18  2023-01-19  Product2  124.0  North
19  2023-01-20  Product3  732.0   West
20  2023-01-21  Product2    0.0   West
21  2023-01-22  Product3  296.0   West
22  2023-01-23  Product2  737.0   West
23  2023-01-24  Product3  531.0   East
24  2023-01-25  Product2  834.0  North

In [17]:
df_filled=df.fillna(0)

In [18]:
## filling missing values with the mean os the column
df['Sales_fillNa']=df['Sales'].fillna(df['Sales'].mean())
df

          Date   Product  Sales Region  Sales_fillNa
0   2023-01-01  Product3  738.0   West         738.0
1   2023-01-02  Product2  868.0  North         868.0
2   2023-01-03  Product2  554.0   West         554.0
3   2023-01-04  Product1  618.0  South         618.0
4   2023-01-05  Product3  501.0   East         501.0
5   2023-01-06  Product1    NaN   West         554.0
6   2023-01-07  Product3  339.0  South         339.0
7   2023-01-08  Product3  280.0  South         280.0
8   2023-01-09  Product2  806.0  North         806.0
9   2023-01-10  Product2  816.0  South         816.0
10  2023-01-11  Product3  469.0   West         469.0
11  2023-01-12  Product3    NaN   East         554.0
12  2023-01-13  Product3    NaN   East         554.0
13  2023-01-14  Product3  676.0   East         676.0
14  2023-01-15  Product1  183.0  South         183.0
15  2023-01-16  Product1  424.0  South         424.0
16  2023-01-17  Product1    NaN  South         554.0
17  2023-01-18  Product1    NaN  South         554.0
18  2023-01-19  Product2  124.0  North         124.0
19  2023-01-20  Product3  732.0   West         732.0
20  2023-01-21  Product2    NaN   West         554.0
21  2023-01-22  Product3  296.0   West         296.0
22  2023-01-23  Product2  737.0   West         737.0
23  2023-01-24  Product3  531.0   East         531.0
24  2023-01-25  Product2  834.0  North         834.0

In [19]:
df.dtypes

Date             object
Product          object
Sales           float64
Region           object
Sales_fillNa    float64
dtype: object

In [23]:
#Renaming Columns
df=df.rename(columns={'Date':'Sales Date'})
df.head()

   Sales Date   Product  Sales Region  Sales_fillNa
0  2023-01-01  Product3  738.0   West         738.0
1  2023-01-02  Product2  868.0  North         868.0
2  2023-01-03  Product2  554.0   West         554.0
3  2023-01-04  Product1  618.0  South         618.0
4  2023-01-05  Product3  501.0   East         501.0

In [26]:
## Change datatypes
df['Sales_new']=df['Sales'].fillna(df['Sales'].mean()).astype(int)
df.head()

   Sales Date   Product  Sales Region  Sales_fillNa  Sales_new
0  2023-01-01  Product3  738.0   West         738.0        738
1  2023-01-02  Product2  868.0  North         868.0        868
2  2023-01-03  Product2  554.0   West         554.0        554
3  2023-01-04  Product1  618.0  South         618.0        618
4  2023-01-05  Product3  501.0   East         501.0        501

In [29]:
df['New Value']=df['Sales'].apply(lambda x:x*2)
df.head()

   Sales Date   Product  Sales Region  Sales_fillNa  Sales_new  New Value
0  2023-01-01  Product3  738.0   West         738.0        738     1476.0
1  2023-01-02  Product2  868.0  North         868.0        868     1736.0
2  2023-01-03  Product2  554.0   West         554.0        554     1108.0
3  2023-01-04  Product1  618.0  South         618.0        618     1236.0
4  2023-01-05  Product3  501.0   East         501.0        501     1002.0

In [30]:
## Data Aggregating AND Grouping

df.head()

   Sales Date   Product  Sales Region  Sales_fillNa  Sales_new  New Value
0  2023-01-01  Product3  738.0   West         738.0        738     1476.0
1  2023-01-02  Product2  868.0  North         868.0        868     1736.0
2  2023-01-03  Product2  554.0   West         554.0        554     1108.0
3  2023-01-04  Product1  618.0  South         618.0        618     1236.0
4  2023-01-05  Product3  501.0   East         501.0        501     1002.0

In [32]:
grouped_mean=df.groupby('Product')['Sales'].mean()
print(grouped_mean)

Product
Product1    408.333333
Product2    677.000000
Product3    506.888889
Name: Sales, dtype: float64

In [34]:
grouped_sum=df.groupby(['Product','Region'])['Sales'].sum()
print(grouped_sum)

Product   Region
Product1  South     1225.0
          West         0.0
Product2  North     2632.0
          South      816.0
          West      1291.0
Product3  East      1708.0
          South      619.0
          West      2235.0
Name: Sales, dtype: float64

In [35]:
df.groupby(['Product','Region'])['Sales'].mean()

Product   Region
Product1  South     408.333333
          West             NaN
Product2  North     658.000000
          South     816.000000
          West      645.500000
Product3  East      569.333333
          South     309.500000
          West      558.750000
Name: Sales, dtype: float64

In [37]:
## aggreate multiple functions
grouped_agg=df.groupby('Region')['Sales'].agg(['mean','sum','count'])

grouped_agg

              mean     sum  count
Region
East    569.333333  1708.0      3
North   658.000000  2632.0      4
South   443.333333  2660.0      6
West    587.666667  3526.0      6

In [38]:
## Merging and  Joining Dataframnes
# Create sample DataFrames

df1 = pd.DataFrame({'Key': ['A', 'B', 'C'], 'Value1': [1, 2, 3]})
df2 = pd.DataFrame({'Key': ['A', 'B', 'D'], 'Value2': [4, 5, 6]})

In [39]:
df1

  Key  Value1
0   A       1
1   B       2
2   C       3

In [40]:
df2

  Key  Value2
0   A       4
1   B       5
2   D       6

In [41]:
# Merge Dataframe on the 'Key Columns'
pd.merge(df1,df2,on="Key",how='inner')

  Key  Value1  Value2
0   A       1       4
1   B       2       5

In [42]:
pd.merge(df1,df2,on="Key",how="outer")

  Key  Value1  Value2
0   A     1.0     4.0
1   B     2.0     5.0
2   C     3.0     NaN
3   D     NaN     6.0

In [44]:
pd.merge(df1,df2,on="Key",how="left")

  Key  Value1  Value2
0   A       1     4.0
1   B       2     5.0
2   C       3     NaN

In [45]:
pd.merge(df1,df2,on="Key",how="right")

  Key  Value1  Value2
0   A     1.0       4
1   B     2.0       5
2   D     NaN       6